'use client';

import { useState, useRef } from 'react';

export default function HtmlToPdfTool() {
  const [htmlInput, setHtmlInput] = useState('');
  const [error, setError] = useState('');
  const [mode, setMode] = useState<'html' | 'url'>('html');
  const [urlInput, setUrlInput] = useState('');

  const convertWithPrint = () => {
    if (mode === 'html' && !htmlInput.trim()) {
      setError('Please paste some HTML content first.');
      return;
    }
    if (mode === 'url' && !urlInput.trim()) {
      setError('Please enter a URL.');
      return;
    }

    setError('');

    // Open in new window and trigger print (browser handles PDF)
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      setError('Popup blocked. Please allow popups for this site.');
      return;
    }

    const htmlContent = mode === 'html'
      ? htmlInput
      : `<html><body style="font-family:sans-serif;padding:20px"><p>For URL conversion, please open the URL, press Ctrl+U to copy the source HTML, and paste it into the HTML tab.</p></body></html>`;

    printWindow.document.write(`<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Converted Document</title>
  <style>
    @page { 
      margin: 0; /* Removes headers, footers, and page margins */
    }
    @media print {
      * {
        -webkit-print-color-adjust: exact !important;
        print-color-adjust: exact !important;
      }
      body { 
        margin: 0; 
      }
      .no-print { display: none !important; }
    }
    body { font-family: sans-serif; padding: 20px; }
    .print-bar {
      position: fixed; top: 0; left: 0; right: 0;
      background: #4f46e5; color: white;
      padding: 12px 20px; display: flex; align-items: center;
      gap: 12px; z-index: 1000; font-family: sans-serif;
    }
    .print-btn {
      background: white; color: #4f46e5;
      border: none; padding: 8px 20px; border-radius: 8px;
      font-weight: bold; cursor: pointer; font-size: 14px;
    }
    .close-btn { background: transparent; color: white; border: 1px solid rgba(255,255,255,0.4); padding: 8px 12px; border-radius: 8px; cursor: pointer; font-size: 14px; }
    .content-area { padding-top: 60px; }
  </style>
</head>
<body>
  <div class="print-bar no-print">
    <span>⚡ Save as PDF: Click "Print" → Select "Save as PDF"</span>
    <button class="print-btn" onclick="window.print()">🖨️ Print / Save as PDF</button>
    <button class="close-btn" onclick="window.close()">✕ Close</button>
  </div>
  <div class="content-area">
    ${htmlContent}
  </div>
  <script>
    // Auto trigger print dialog after content loads
    window.onload = () => {
      setTimeout(() => window.print(), 500);
    };
  </script>
</body>
</html>`);
    printWindow.document.close();
  };

  const loadSample = () => {
    setHtmlInput(`<!DOCTYPE html>
<html>
<head><title>Sample Document</title></head>
<body style="font-family: Arial, sans-serif; padding: 40px; max-width: 700px; margin: 0 auto;">
  <h1 style="color: #4f46e5; border-bottom: 2px solid #4f46e5; padding-bottom: 10px;">Sample Report</h1>
  <p><strong>Date:</strong> March 28, 2026</p>
  <p>This is a sample HTML document that will be converted to PDF. You can replace this content with your own HTML.</p>
  <h2>Section 1: Introduction</h2>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
  <ul>
    <li>Feature One — important detail</li>
    <li>Feature Two — another important point</li>
    <li>Feature Three — final consideration</li>
  </ul>
  <h2>Section 2: Data Table</h2>
  <table border="1" cellpadding="8" cellspacing="0" style="border-collapse:collapse;width:100%">
    <tr style="background:#4f46e5;color:white"><th>Name</th><th>Value</th><th>Status</th></tr>
    <tr><td>Item A</td><td>₹1,200</td><td>Active</td></tr>
    <tr style="background:#f8f8f8"><td>Item B</td><td>₹3,400</td><td>Pending</td></tr>
    <tr><td>Item C</td><td>₹5,600</td><td>Active</td></tr>
  </table>
  <p style="margin-top:30px;color:#666;font-size:13px;">Generated by Microtools HTML to PDF Converter</p>
</body>
</html>`);
    setMode('html');
    setError('');
  };

  return (
    <div className="space-y-5">
      {/* Mode Tabs */}
      <div className="flex rounded-xl border border-border overflow-hidden">
        <button
          onClick={() => { setMode('html'); setError(''); }}
          className={`flex-1 py-2.5 text-sm font-semibold transition-all ${mode === 'html' ? 'bg-primary text-primary-foreground' : 'bg-card text-muted-foreground hover:text-foreground'}`}
        >
          📝 Paste HTML
        </button>
        <button
          onClick={() => { setMode('url'); setError(''); }}
          className={`flex-1 py-2.5 text-sm font-semibold transition-all ${mode === 'url' ? 'bg-primary text-primary-foreground' : 'bg-card text-muted-foreground hover:text-foreground'}`}
        >
          🔗 From URL
        </button>
      </div>

      {mode === 'html' ? (
        <div className="space-y-3 animate-fade-in-up">
          <div className="flex items-center justify-between">
            <label className="text-sm font-semibold text-foreground">HTML Content</label>
            <button
              onClick={loadSample}
              className="text-xs px-3 py-1 rounded-lg bg-muted text-muted-foreground hover:text-foreground transition-colors border border-border"
            >
              Load Sample
            </button>
          </div>
          <textarea
            value={htmlInput}
            onChange={(e) => { setHtmlInput(e.target.value); setError(''); }}
            placeholder={'<html>\n  <body>\n    <h1>My Document</h1>\n    <p>Paste your full HTML here...</p>\n  </body>\n</html>'}
            className="w-full h-64 p-4 rounded-xl border border-border bg-muted/20 text-sm font-mono text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary/50 resize-y"
            spellCheck={false}
          />
          <p className="text-xs text-muted-foreground">
            Paste full HTML including &lt;html&gt;, &lt;head&gt;, and &lt;body&gt; tags for best results.
          </p>
        </div>
      ) : (
        <div className="space-y-3 animate-fade-in-up">
          <label className="text-sm font-semibold text-foreground">Webpage URL</label>
          <div className="p-4 rounded-xl border border-amber-200 dark:border-amber-800 bg-amber-50 dark:bg-amber-900/20">
            <p className="text-sm text-amber-700 dark:text-amber-400 leading-relaxed">
              ⚠️ <strong>Browser limitation:</strong> Converting full external URLs directly is blocked by browser security measures (CORS). For best results, open the webpage, press <kbd className="px-1.5 py-0.5 mx-1 rounded bg-amber-100 dark:bg-amber-800 text-[10px] font-mono whitespace-nowrap">Ctrl + U</kbd> to view source, copy it, and paste it into the <strong>Paste HTML</strong> tab.
            </p>
          </div>
          <input
            type="url"
            value={urlInput}
            onChange={(e) => setUrlInput(e.target.value)}
            placeholder="https://example.com/page"
            className="w-full p-3 rounded-xl border border-border bg-muted/20 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary/50"
          />
        </div>
      )}

      {error && (
        <div className="p-3 rounded-lg bg-destructive/10 border border-destructive/20 text-destructive text-sm font-medium">{error}</div>
      )}

      {/* Convert Action */}
      <button
        onClick={convertWithPrint}
        className="w-full py-4 rounded-xl bg-gradient-to-r from-indigo-500 to-violet-500 text-white font-bold text-base hover:opacity-90 transition-all shadow-md flex items-center justify-center gap-2"
      >
        <svg className="w-5 h-5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" /></svg>
        Convert & Save as PDF
      </button>

      <div className="p-4 rounded-xl border border-border bg-muted/20">
        <p className="text-sm font-semibold text-foreground mb-2 flex items-center gap-2">
          <span>💡</span> How it works:
        </p>
        <ol className="text-xs text-muted-foreground space-y-2 list-decimal list-inside pl-1">
          <li>Paste your HTML or click <strong>Load Sample</strong>.</li>
          <li>Click <strong>Convert & Save as PDF</strong>.</li>
          <li>A clean preview window will open and automatically launch the Print dialog.</li>
          <li>Change the Destination to <strong>Save as PDF</strong> and click Save.</li>
        </ol>
      </div>

      <div className="flex items-start gap-2 p-3 rounded-lg bg-indigo-50/50 dark:bg-indigo-950/20 border border-indigo-100 dark:border-indigo-900 text-xs text-muted-foreground leading-relaxed">
        <span className="text-indigo-500 text-base leading-none">ℹ️</span>
        <p>
          We rely on your browser's native PDF engine instead of a canvas library. This guarantees <strong>perfect text rendering</strong> (you can copy/paste text from the PDF), exact CSS layouts, and multi-page support — zero blank pages or blurry text.
        </p>
      </div>
    </div>
  );
}
